version: "3.9"

services:
  iep1:
    build: ./IEP1_forecasting
    container_name: iep1
    ports:
      - "8001:8001" 
    networks:
      - app-network

  iep2:
    build: ./IEP2_drought_assessment
    container_name: iep2
    ports:
      - "8002:8002"
    networks:
      - app-network

  iep3:
    build: ./IEP3_water_availability
    container_name: iep3
    ports:
      - "8003:8003"
    networks:
      - app-network

  eep:
    build: ./EEP_interface
    container_name: eep
    ports:
      - "8004:8004"
    depends_on:
      - iep1
      - iep2
      - iep3
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


# {
#   "id": "/subscriptions/a58965fa-3054-486e-b069-fa4a5026626b/resourceGroups/myContainerAppsRG/providers/Microsoft.App/managedEnvironments/myContainerAppsEnv",
#   "location": "East US",
#   "name": "myContainerAppsEnv",
#   "properties": {
#     "appInsightsConfiguration": null,
#     "appLogsConfiguration": {
#       "destination": "log-analytics",
#       "logAnalyticsConfiguration": {
#         "customerId": "23497b74-ebb7-4e23-b2ee-0d41437c254d",
#         "dynamicJsonColumns": false,
#         "sharedKey": null
#       }
#     },
#     "availabilityZones": null,
#     "customDomainConfiguration": {
#       "certificateKeyVaultProperties": null,
#       "certificatePassword": null,
#       "certificateValue": null,
#       "customDomainVerificationId": "62C4FE8FECC18FCAE7144F932400E5402E2C17B36D8A9791F196C87990D99E9B",
#       "dnsSuffix": null,
#       "expirationDate": null,
#       "subjectName": null,
#       "thumbprint": null
#     },
#     "daprAIConnectionString": null,
#     "daprAIInstrumentationKey": null,
#     "daprConfiguration": {
#       "version": "1.13.6-msft.2"
#     },
#     "defaultDomain": "happybay-635c300a.eastus.azurecontainerapps.io",
#     "diskEncryptionConfiguration": null,
#     "eventStreamEndpoint": "https://eastus.azurecontainerapps.dev/subscriptions/a58965fa-3054-486e-b069-fa4a5026626b/resourceGroups/myContainerAppsRG/managedEnvironments/myContainerAppsEnv/eventstream",
#     "infrastructureResourceGroup": null,
#     "kedaConfiguration": {
#       "version": "2.16.1"
#     },
#     "openTelemetryConfiguration": null,
#     "peerAuthentication": {
#       "mtls": {
#         "enabled": false
#       }
#     },
#     "peerTrafficConfiguration": {
#       "encryption": {
#         "enabled": false
#       }
#     },
#     "provisioningState": "Succeeded",
#     "publicNetworkAccess": "Enabled",
#     "staticIp": "128.203.117.244",
#     "vnetConfiguration": null,
#     "workloadProfiles": [
#       {
#         "enableFips": false,
#         "name": "Consumption",
#         "workloadProfileType": "Consumption"
#       }
#     ],
#     "zoneRedundant": false
#   },
#   "resourceGroup": "myContainerAppsRG",
#   "systemData": {
#     "createdAt": "2025-04-26T14:05:46.956778",
#     "createdBy": "iza04@mail.aub.edu",
#     "createdByType": "User",
#     "lastModifiedAt": "2025-04-26T14:05:46.956778",
#     "lastModifiedBy": "iza04@mail.aub.edu",
#     "lastModifiedByType": "User"
#   },
#   "type": "Microsoft.App/managedEnvironments"
# }