version: "3.9"

services:
  iep1:
    build: ./IEP1_forecasting
    container_name: iep1
    ports:
      - "8001:8001"
    networks:
      - app-network

  iep2:
    build: ./IEP2_drought_assessment
    container_name: iep2
    ports:
      - "8002:8002"
    networks:
      - app-network

  iep3:
    build: ./IEP3_water_availability
    container_name: iep3
    ports:
      - "8003:8003"
    networks:
      - app-network

  eep:
    build: ./EEP_interface
    container_name: eep
    ports:
      - "8004:8004"
    depends_on:
      - iep1
      - iep2
      - iep3
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus config file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
